# This is a basic workflow to help you get started with Actions

name: Modular CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    outputs:
      ARTIFACT_ID: ${{ steps.Build_and_upload_package_step.outputs.ARTIFACT_ID }}
    steps:
      - name: Checkout	
        uses: actions/checkout@v3
      - name: Deploy the package on the DataMiner System step
        uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1
        id: Build_and_upload_package_step
        with:
          api-key: ${{ secrets.HERA_KEY }}
          solution-path: './AutomationScript.sln'
          package-name: 'MyPackageName'
          version: '1.0.1'
          stage: Upload

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1
        with:
          api-key: ${{ secrets.HERA_KEY }}
          stage: Deploy
          timeout: '300'
          artifact-id: ${{ needs.build.outputs.ARTIFACT_ID }}
